name: Cypress Tests demo

on: push

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with: 
          node-version: '20.x'
          cache: npm
      - run: |
          npm install --save-dev
          npm install cypress
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          # Disable running of tests within install job
          runTests: false
          start: npm start
