name: run cypress test for practice
on:
  push:
    branches:
    - e2e

jobs:
  cypress-e2e-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install depedencies
        run: npm install
      - name: Cypress run e2e
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: |
            e2e/saucedemo/*.cy.js
            e2e/1-getting-started
          report: true
